POST http://localhost:4000/api/new-user
Content-Type: application/json

{
    "name": "peter",
    "lastname": "R",
    "email": "petr@gmail.com",
    "age": "20",
    "saldo": "5",
    "password": "12345"
}

###
POST http://localhost:4000/api/login
Content-Type: application/json

{
    "email": "petr@gmail.com",
    "password": "12345"
}

###
GET http://localhost:4000/api/info-user
Content-Type: application/json

