POST http://localhost:3000/api/new-user
Content-Type: application/json

{

    "email": "hola@gmail.com",
    "password": "12345"
}

###
POST http://localhost:3000/api/login
Content-Type: application/json
Accept: application/json

{
    "email": "hola@gmail.com",
    "password": "1235"
}

###
POST http://localhost:3000/api/info-user
Content-Type: application/json
Accept: application/json

{
    "email": "hola@gmail.com"
}

###
POST http://localhost:3000/api/update
Content-Type: application/json

{
    "name": "UPDATE API", 
    "lastname": "apellido",
    "cedula": "cedula",
    "age": 25,
    "email": "hola@gmail.com"
}

###
POST http://localhost:3000/api/pago
Content-Type: application/json

{
    "name": "UPDATE API", 
    "lastname": "apellido",
    "cedula": "cedula",
    "age": 25,
    "email": "hola@gmail.com",
    "saldo": "10"
}


###
GET http://localhost:3000/api/logout